### ISSUE TITLE
Using CAN bus on MCU k1921vk

### ISSUE THREAD

**Issue by brightproject** [DCVostok/framework-k1921vk-freertos#1]
Hello @kenny5660
Studying the documentation

> https://niiet.ru/wp-content/uploads/2023/02/%D0%A0%D0%9F-1921%D0%92%D0%9A035.pdf

I saw the possibility of working with a microcontroller with a `CAN` bus.
I have a transceiver `mcp2551`

![mcp2551](https://github.com/user-attachments/assets/da3d8aeb-25ed-4bd2-baf5-758397523f00)

Are there any examples of using a microcontroller with this module or similar ones?

`P.S.` I posted the issue in this thread because there is no way to ask questions in the `.pio` thread

> https://github.com/DCVostok/pio_platform_k1921vk

It would be great if the repository opened the possibility of discussions.

**Comment by kenny5660** [comment]
I turned on "issues" at https://github.com/DCVostok/pio_platform_k1921vk 
Please move this issue there.
